FROM public.ecr.aws/lambda/python:3.11

COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

COPY agent.py bedrock_agent.py db_schema.py lambda_handler.py .

CMD ["lambda_handler.handler"]
